spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:sqlserver://localhost;encrypt=False;database=TAQASEEM
    username: sa
    password: sa12345!!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: ${INIT_SQL:never}
application:
  security:
    jwt:
      secret-key: dc1acb74ab12378ad211e350138ee7b357c1a51adc1acb74ab12378ad211e350138ee7b357c1a51adc1acb74ab12378ad211e350138ee7b357c1a51adc1acb74ab12378ad211e350138ee7b357c1a51a
      expiration: 30
      refresh-token:
        expiration: 129600
logging:
  level:
    root: debug