spring:
  config:
    activate:
      on-profile: local-clerk
  datasource:
    url: jdbc:sqlserver://localhost;encrypt=False;database=TAQASEEM
    username: sa
    password: Sa12341234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: on
  sql:
    init:
      mode: ${INIT_SQL:never}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
    test-rollback-on-update: true
clerk:
  secret-key: sk_test_5tlKG6wjLbSWcmqN9N7xrPUzaILBLmGAFP31sEQTDl