FROM mcr.microsoft.com/mssql/server:2022-latest
#USER root
WORKDIR /usr/src/sql
COPY . /usr/src/sql
ENV MSSQL_SA_PASSWORD Sa12341234
ENV SA_PASSWORD Sa12341234
ENV ACCEPT_EULA Y
ENTRYPOINT /opt/mssql/bin/sqlservr 
