services:
  backend:
    container_name: taqaseem-backend
    image: fahadalshoshan/taqaseem-be:latest
    environment:
      - "JAVA_TOOL_OPTIONS=-Duser.timezone=\"Asia/Riyadh\""
      - "SPRING_PROFILES_ACTIVE=local"
    security_opt:
      - label:disable
    volumes:
      - /home/dev/taqaseem_logs:/home/dev/taqaseem_logs
    network_mode: "host"
